config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  resources :users, :businesses do
    resources :comments, :reviews, :photos, :hours
  end

  get '/test' => 'pages#test'
  patch '/hours' => 'hours#update'

  get 'businesses/index'

  # Authentication Routes
  get '/signup' => 'users#new'
  post '/signup' => 'users#post'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController

	before_action :require_user, only: [:contact, :help]
	before_action :require_admin, only: [:new, :create, :edit]

	def index
		# @businesses = Business.all

  	if params[:query]
		query = params[:query]
		@businesses = Business.where(:name => query).page(params[:page])
   	else
    	@businesses = Business.order(:name).page(params[:page])
    end		

	end

	def new
		@business = Business.new
	end

	def create
		@business = Business.new(business_params)

		if @business.save
			flash[:success] = "You've successfully added your business."
			redirect_to edit_business_path(@business.id)
		else
			flash[:failure] = "Something went wrong. Your business wasn't created."
			render new
		end
	end

	def show
		# Google Maps API
		url = "https://maps.googleapis.com/maps/api/js?key="
  	key = ENV['GOOGLE_MAPS']
  	@endpoint = url + key

		@business = Business.find(params[:id])
		@photo = @business.photos.new

		@user = User.find_by_id(@business.reviews)
	end

	def edit
		@business = Business.find(params[:id])
		# @hours = Hour.new unless Hour.exists?(business_id: @business.id) do Hour.new end
		if Hour.exists?(business_id: @business.id)
			@hours = Hour.find_by_business_id(@business.id) 
		else 
			@hours = Hour.new 
		end
	end

	def update
		@business = Business.find(params[:id])

		if @business.update_attributes(business_params)
			redirect_to business_path
		else
			render edit
		end
	end

	def destroy
		@business = Business.find(params[:id])
		@business.reviews.destroy_all
    @business.destroy
    redirect_to businesses_path
	end

	private
		def business_params
			params.require(:business).permit(:name, :address, :address_2, :city, :state, :zip, :phone, :website)
		end
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/views/businesses/_hours.html.erb
<option value='12:00AM'>12:00AM (midnight)</option>
<option value='12:30AM'>12:30AM</option>
<option value='1:00AM'>1:00AM</option>
<option value='1:30AM'>1:30AM</option>
<option value='2:00AM'>2:00AM</option>
<option value='2:30AM'>2:30AM</option>
<option value='3:00AM'>3:00AM</option>
<option value='3:30AM'>3:30AM</option>
<option value='4:00AM'>4:00AM</option>
<option value='4:30AM'>4:30AM</option>
<option value='5:00AM'>5:00AM</option>
<option value='5:30AM'>5:30AM</option>
<option value='6:00AM'>6:00AM</option>
<option value='6:30AM'>6:30AM</option>
<option value='7:00AM'>7:00AM</option>
<option value='7:30AM'>7:30AM</option>
<option value='8:00AM'>8:00AM</option>
<option value='8:30AM'>8:30AM</option>
<option value='9:00AM'>9:00AM</option>
<option value='9:30AM'>9:30AM</option>
<option value='10:00AM'>10:00AM</option>
<option value='10:30AM'>10:30AM</option>
<option value='11:00AM'>11:00AM</option>
<option value='11:30AM'>11:30AM</option>
<option value='12:00PM'>12:00PM (noon)</option>
<option value='12:30PM'>12:30PM</option>
<option value='1:00PM'>1:00PM</option>
<option value='1:30PM'>1:30PM</option>
<option value='2:00PM'>2:00PM</option>
<option value='2:30PM'>2:30PM</option>
<option value='3:00PM'>3:00PM</option>
<option value='3:30PM'>3:30PM</option>
<option value='4:00PM'>4:00PM</option>
<option value='4:30PM'>4:30PM</option>
<option value='5:00PM'>5:00PM</option>
<option value='5:30PM'>5:30PM</option>
<option value='6:00PM'>6:00PM</option>
<option value='6:30PM'>6:30PM</option>
<option value='7:00PM'>7:00PM</option>
<option value='7:30PM'>7:30PM</option>
<option value='8:00PM'>8:00PM</option>
<option value='8:30PM'>8:30PM</option>
<option value='9:00PM'>9:00PM</option>
<option value='9:30PM'>9:30PM</option>
<option value='10:00PM'>10:00PM</option>
<option value='10:30PM'>10:30PM</option>
<option value='11:00PM'>11:00PM</option>
<option value='11:30PM'>11:30PM</option>

app/views/businesses/_map.html.erb
<script type="text/javascript">
var geocoder;
var map;

function initialize() {
  geocoder = new google.maps.Geocoder();

  var address = "<%= "#{@business.address}, #{@business.city}, #{@business.state}, #{@business.zip}" %>"
  geocoder.geocode( { 'address': address}, function(results, status) {
    if (status == google.maps.GeocoderStatus.OK) {
      map.setCenter(results[0].geometry.location);
      var marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location
      });
      marker.setAnimation(google.maps.Animation.BOUNCE);
    } else {
      console.log('Geocode was not successful for the following reason: ' + status);
    }
  });

  var mapOptions = {
    zoom: 15,
  }
  map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
}

  google.maps.event.addDomListener(window, 'load', initialize);
  // initialize();
</script>

app/views/businesses/_menu_bar.html.erb
<div class="menubar">
  <div class="ui secondary menu">
    <%= link_to raw("<i class='home icon'></i> Home"), root_path, class: "item" %>
    <%= link_to raw("<i class='arrow left icon'></i> Back to #{@business.name}"), business_path, class: "item" if current_user && current_user.admin? && params[:action] == 'edit' %>
    <%= link_to raw("<i class='food icon'></i> Happy Hour Listing"), businesses_path, class: "item" %>
    <%= link_to raw("<i class='plus icon'></i> Add Review"), new_business_review_path(params[:id]), class: "item" if current_user && params[:action] == 'show' %>
    <% if current_user %>
    <%= link_to raw("<i class='plus icon'></i> Add Business"), new_business_path, class: "item" if current_user && current_user.admin? %>
    <%= link_to raw("<i class='edit icon'></i> Edit Business"), edit_business_path, class: "item" if current_user.admin? && params[:action] == 'show' %>
    <% if current_user.admin? && params[:action] == 'show' %><%= link_to raw("<i class='remove icon'></i> Delete Business"), :business, class: "item", method: :delete, data: {confirm: "Are you sure you want to delete this listing? This will remove all associated reviews, photos, and business information."} %><% end %>
    <% end %>
    <div class="right menu">
    <%= link_to raw("<i class='user icon'></i> About Me"), user_path(current_user.id), class: "item" if current_user %>
    </div>
  </div>
</div>

app/views/businesses/edit.html.erb
<%= render 'businesses/menu_bar' %>

<div class="ui center aligned dividing header"><%= link_to @business.name, business_path %></div>

<div class="ui two column grid">
  <div class="column">
    <div class="ui small form segment">
      <h4 class="ui dividing header">Edit Business</h4> 
      <%= form_for @business do |f| %>
      <div class="field">
        <label>Business Name</label>
        <%= f.text_field :name, class: "ui input", placeholder: "Name of business..." %>
      </div>
      <div class="field">
        <label>Address</label>
        <%= f.text_field :address, class: "ui input", placeholder: "1234 Spooner St." %>
      </div>
      <div class="field">
        <label>Address 2</label>
        <%= f.text_field :address_2, class: "ui input", placeholder: "Unit 1" %>
      </div>
      <div class="field">
        <label>City</label>
        <%= f.text_field :city, class: "ui input", placeholder: "Los Angeles" %>
      </div>
      <div class="two fields">
        <div class="field">
        <label>State</label>
        <%= f.text_field :state, class: "ui input", placeholder: "Los Angeles" %> 
        </div>
        <div class="field">
        <label>ZIP</label>
        <%= f.text_field :zip, class: "ui input", placeholder: "Los Angeles" %>          
        </div>
      </div>
        <div class="field">
        <label>Phone Number</label>
        <%= f.telephone_field :phone, class: "ui input" %>          
        </div>
        <div class="field">
        <label>Website URL</label>
        <%= f.text_field :website, class: "ui input", placeholder: "http://" %>          
        </div>   
      <%= f.submit "Update Business Details", class: "ui button" %>
      <% end %>
    </div>

  </div>
  
  <div class="column">
    <div class="ui small form segment">
      <h4 class="ui dividing header">Hours of Operation</h4>
      <%= form_for [@business, @hours] do |f| %>
      <div class="two fields"> <!-- Monday -->
        <div class="field">
          <h5 class="ui center aligned dividing header">Open</h5>
          <%= select_tag 'hour[mon_open]', "<option value='#{@hours.mon_open}'>Monday - #{@hours.mon_open.strftime('%l:%M%p') if @hours.mon_open}</option>#{render 'businesses/hours'}".html_safe, class: "ui search dropdown normalize", id: "hour_mon_open" %>
        </div>
        <div class="field">
          <h5 class="ui center aligned dividing header">Close</h5>
          <%= select_tag 'hour[mon_close]', "<option value='#{@hours.mon_close}'>Monday - #{@hours.mon_close.strftime('%l:%M%p') if @hours.mon_close}</option>#{render 'businesses/hours'}".html_safe, class: "ui search dropdown normalize", id: "hour_mon_close" %>
        </div>
      </div>
      <div class="two fields"> <!-- Tuesday -->
        <div class="field">
          <%= select_tag 'hour[tue_open]', "<option value='#{@hours.tue_open}'>Tuesday - #{@hours.tue_open.strftime('%l:%M%p') if @hours.tue_open}</option>#{render 'businesses/hours'}".html_safe, class: "ui search dropdown normalize", id: "hour_tue_open" %>
        </div>
        <div class="field">
          <%= select_tag 'hour[tue_close]', "<option value='#{@hours.tue_close}'>Tuesday - #{@hours.tue_close.strftime('%l:%M%p') if @hours.tue_close}</option>#{render 'businesses/hours'}".html_safe, class: "ui search dropdown normalize", id: "hour_tue_close" %>
        </div>
      </div>
      <div class="two fields"> <!-- Wednesday -->
        <div class="field">
          <%= select_tag 'hour[wed_open]', "<option value='#{@hours.wed_open}'>Wednesday - #{@hours.wed_open.strftime('%l:%M%p') if @hours.wed_open}</option>#{render 'businesses/hours'}".html_safe, class: "ui search dropdown normalize", id: "hour_wed_open" %>
        </div>
        <div class="field">
          <%= select_tag 'hour[wed_close]', "<option value='#{@hours.wed_close}'>Wednesday - #{@hours.wed_close.strftime('%l:%M%p') if @hours.wed_close}</option>#{render 'businesses/hours'}".html_safe, class: "ui search dropdown normalize", id: "hour_wed_close" %>
        </div>
      </div>
      <div class="two fields"> <!-- Thursday -->
        <div class="field">
          <%= select_tag 'hour[thu_open]', "<option value='#{@hours.thu_open}'>Thursday - #{@hours.thu_open.strftime('%l:%M%p') if @hours.thu_open}</option>#{render 'businesses/hours'}".html_safe, class: "ui search dropdown normalize", id: "hour_thu_open" %>
        </div>
        <div class="field">
          <%= select_tag 'hour[thu_close]', "<option value='#{@hours.thu_close}'>Thursday - #{@hours.thu_close.strftime('%l:%M%p') if @hours.thu_close}</option>#{render 'businesses/hours'}".html_safe, class: "ui search dropdown normalize", id: "hour_thu_close" %>
        </div>
      </div>
      <div class="two fields"> <!-- Friday -->
        <div class="field">
          <%= select_tag 'hour[fri_open]', "<option value='#{@hours.fri_open}'>Friday - #{@hours.fri_open.strftime('%l:%M%p') if @hours.fri_open}</option>#{render 'businesses/hours'}".html_safe, class: "ui search dropdown normalize", id: "hour_fri_open" %>
        </div>
        <div class="field">
          <%= select_tag 'hour[fri_close]', "<option value='#{@hours.fri_close}'>Friday - #{@hours.fri_close.strftime('%l:%M%p') if @hours.fri_close}</option>#{render 'businesses/hours'}".html_safe, class: "ui search dropdown normalize", id: "hour_fri_close" %>
        </div>
      </div>
      <div class="two fields"> <!-- Saturday -->
        <div class="field">
          <%= select_tag 'hour[sat_open]', "<option value='#{@hours.sat_open}'>Saturday - #{@hours.sat_open.strftime('%l:%M%p') if @hours.sat_open}</option>#{render 'businesses/hours'}".html_safe, class: "ui search dropdown normalize", id: "hour_sat_open" %>
        </div>
        <div class="field">
          <%= select_tag 'hour[sat_close]', "<option value='#{@hours.sat_close}'>Saturday - #{@hours.sat_close.strftime('%l:%M%p') if @hours.sat_close}</option>#{render 'businesses/hours'}".html_safe, class: "ui search dropdown normalize", id: "hour_sat_close" %>
        </div>
      </div>
      <div class="two fields"> <!-- Sunday -->
        <div class="field">
          <%= select_tag 'hour[sun_open]', "<option value='#{@hours.sun_open}'>Sunday - #{@hours.sun_open.strftime('%l:%M%p') if @hours.sun_open}</option>#{render 'businesses/hours'}".html_safe, class: "ui search dropdown normalize", id: "hour_sun_open" %>
        </div>
        <div class="field">
          <%= select_tag 'hour[sun_close]', "<option value='#{@hours.sun_close}'>Sunday - #{@hours.sun_close.strftime('%l:%M%p') if @hours.sun_close}</option>#{render 'businesses/hours'}".html_safe, class: "ui search dropdown normalize", id: "hour_sun_close" %>
        </div>
      </div>
      <%= f.submit "Update Business Hours", class: "ui button" %>
      <% end %>
      </div>

    <div class="ui small form segment">
      <h4 class="ui dividing header">Happy Hour</h4>
      <%= form_for [@business, @hours] do |f| %>
      <div class="two fields"> <!-- Monday -->
        <div class="field">
          <h5 class="ui center aligned dividing header">Start</h5>
          <%= select_tag 'hour[mon_start]', "<option value='#{@hours.mon_start}'>Monday - #{@hours.mon_start.strftime('%l:%M%p') if @hours.mon_start}</option>#{render 'businesses/hours'}".html_safe, class: "ui search dropdown normalize", id: "hour_mon_start" %>
        </div>
        <div class="field">
          <h5 class="ui center aligned dividing header">End</h5>
          <%= select_tag 'hour[mon_end]', "<option value='#{@hours.mon_end}'>Monday - #{@hours.mon_end.strftime('%l:%M%p') if @hours.mon_end}</option>#{render 'businesses/hours'}".html_safe, class: "ui search dropdown normalize", id: "hour_mon_end" %>
        </div>
      </div>
      <div class="two fields"> <!-- Tuesday -->
        <div class="field">
          <%= select_tag 'hour[tue_start]', "<option value='#{@hours.tue_start}'>Tuesday - #{@hours.tue_start.strftime('%l:%M%p') if @hours.tue_start}</option>#{render 'businesses/hours'}".html_safe, class: "ui search dropdown normalize", id: "hour_tue_start" %>
        </div>
        <div class="field">
          <%= select_tag 'hour[tue_end]', "<option value='#{@hours.tue_end}'>Tuesday - #{@hours.tue_end.strftime('%l:%M%p') if @hours.tue_end}</option>#{render 'businesses/hours'}".html_safe, class: "ui search dropdown normalize", id: "hour_tue_end" %>
        </div>
      </div>
      <div class="two fields"> <!-- Wednesday -->
        <div class="field">
          <%= select_tag 'hour[wed_start]', "<option value='#{@hours.wed_start}'>Wednesday - #{@hours.wed_start.strftime('%l:%M%p') if @hours.wed_start}</option>#{render 'businesses/hours'}".html_safe, class: "ui search dropdown normalize", id: "hour_wed_start" %>
        </div>
        <div class="field">
          <%= select_tag 'hour[wed_end]', "<option value='#{@hours.wed_end}'>Wednesday - #{@hours.wed_end.strftime('%l:%M%p') if @hours.wed_end}</option>#{render 'businesses/hours'}".html_safe, class: "ui search dropdown normalize", id: "hour_wed_end" %>
        </div>
      </div>
      <div class="two fields"> <!-- Thursday -->
        <div class="field">
          <%= select_tag 'hour[thu_start]', "<option value='#{@hours.thu_start}'>Thursday - #{@hours.thu_start.strftime('%l:%M%p') if @hours.thu_start}</option>#{render 'businesses/hours'}".html_safe, class: "ui search dropdown normalize", id: "hour_thu_start" %>
        </div>
        <div class="field">
          <%= select_tag 'hour[thu_end]', "<option value='#{@hours.thu_end}'>Thursday - #{@hours.thu_end.strftime('%l:%M%p') if @hours.thu_end}</option>#{render 'businesses/hours'}".html_safe, class: "ui search dropdown normalize", id: "hour_thu_end" %>
        </div>
      </div>
      <div class="two fields"> <!-- Friday -->
        <div class="field">
          <%= select_tag 'hour[fri_start]', "<option value='#{@hours.fri_start}'>Friday - #{@hours.fri_start.strftime('%l:%M%p') if @hours.fri_start}</option>#{render 'businesses/hours'}".html_safe, class: "ui search dropdown normalize", id: "hour_fri_start" %>
        </div>
        <div class="field">
          <%= select_tag 'hour[fri_end]', "<option value='#{@hours.fri_end}'>Friday - #{@hours.fri_end.strftime('%l:%M%p') if @hours.fri_end}</option>#{render 'businesses/hours'}".html_safe, class: "ui search dropdown normalize", id: "hour_fri_end" %>
        </div>
      </div>
      <div class="two fields"> <!-- Saturday -->
        <div class="field">
          <%= select_tag 'hour[sat_start]', "<option value='#{@hours.sat_start}'>Saturday - #{@hours.sat_start.strftime('%l:%M%p') if @hours.sat_start}</option>#{render 'businesses/hours'}".html_safe, class: "ui search dropdown normalize", id: "hour_sat_start" %>
        </div>
        <div class="field">
          <%= select_tag 'hour[sat_end]', "<option value='#{@hours.sat_end}'>Saturday - #{@hours.sat_end.strftime('%l:%M%p') if @hours.sat_end}</option>#{render 'businesses/hours'}".html_safe, class: "ui search dropdown normalize", id: "hour_sat_end" %>
        </div>
      </div>
      <div class="two fields"> <!-- Sunday -->
        <div class="field">
          <%= select_tag 'hour[sun_start]', "<option value='#{@hours.sun_start}'>Sunday - #{@hours.sun_start.strftime('%l:%M%p') if @hours.sun_start}</option>#{render 'businesses/hours'}".html_safe, class: "ui search dropdown normalize", id: "hour_sun_start" %>
        </div>
        <div class="field">
          <%= select_tag 'hour[sun_end]', "<option value='#{@hours.sun_end}'>Sunday - #{@hours.sun_end.strftime('%l:%M%p') if @hours.sun_end}</option>#{render 'businesses/hours'}".html_safe, class: "ui search dropdown normalize", id: "hour_sun_end" %>
        </div>
      </div>
      <%= f.submit "Update Happy Hour Details", class: "ui button" %>
      <% end %>
      </div>

    </div>
  </div>

</div>

app/views/businesses/show.html.erb
<script type="text/javascript" src="<%= @endpoint %>"></script>

<%= render 'businesses/menu_bar' %>

<div class="ui grid">
  <div class="sixteen wide column">
    
<div class="map_info_container" style="width: 200px; background: #fff; border: 1px solid darkgray; overflow: hidden; float: right;">
  <div id="map-canvas" style="width: 200px; height: 130px; background: #000;"></div>
  <div id="address_details" style="width: 200px; padding: 6px;">
    <h5 class="normalize">Address:</h5>
    <%= @business.address %> <%= @business.address_2 %><br>
    <%= @business.city %>, <%= @business.state %> <%= @business.zip %><br><br>
    <%= "<b>Phone:</b> #{number_to_phone(@business.phone, area_code: true)}".html_safe if @business.phone %><br><br>
    <%= "<b>Website:</b><br> #{@business.website}".html_safe if @business.website %>
  </div>
</div>

    <div class="photo_business"><%= image_tag @business.photos[@business.photos.length-2].photo.url %></div>

    <h1 class="normalize"><%= @business.name %></h1>
    <p class="normalize"><%= "#{@business.reviews.count} reviews." %></p>
    <br><br>
    <% if current_user %><button class="test ui mini blue button">Add Photo</button><% end %>


  </div>
</div>

<hr style="margin-bottom: 10px;">

<div class="ui grid">
  <div class="eleven wide column">
  <h1 class="ui dividing header">REVIEWS</h1>

<% @business.reviews.order(created_at: :desc).each do |review| %>
    <div class="review_container">
      <div class="review_user">
        <%= image_tag review.user.photo.url, class: "review_avatar" if review.user.photo.url %><strong><%= link_to "#{User.find(review.user_id.to_i).first_name} #{User.find(review.user_id.to_i).last_name}", user_path(review.user_id) unless review.user_id.to_i == 0 %></strong>
      </div>
      <div class="review_body">
        <strong><%= review.title %></strong> - <span class="small_text"><%= "Posted " + time_ago_in_words(review.created_at) + " ago." unless review.created_at.blank? %></span><br>
        <p class="normalize small_text"><b class="small_text">Rating: 5</b></p>
        <p style="padding-top: 8px;"><%= simple_format(review.body) %></p>
      </div>
    </div>
<% end %>

  </div>
  <div class="five wide column">
    <div class="business_detail_column">
      <div class="ui dividing header">Business Hours</div>
        <% if @business.hour %>
        <table>
          <tr><td class="day_column">Monday:</td><td class="hours_column"><%= "#{@business.hour.mon_open.strftime('%l:%M%p')} - #{@business.hour.mon_close.strftime('%l:%M%p')}" if @business.hour.mon_open && @business.hour.mon_close %></td></tr>
          <tr><td class="day_column">Tuesday:</td><td class="hours_column"><%= "#{@business.hour.tue_open.strftime('%l:%M%p')} - #{@business.hour.tue_close.strftime('%l:%M%p')}" if @business.hour.tue_open && @business.hour.tue_close %></td></tr>
          <tr><td class="day_column">Wednesday:</td><td class="hours_column"><%= "#{@business.hour.wed_open.strftime('%l:%M%p')} - #{@business.hour.wed_close.strftime('%l:%M%p')}" if @business.hour.wed_open && @business.hour.wed_close %></td></tr>
          <tr><td class="day_column">Thursday:</td><td class="hours_column"><%= "#{@business.hour.thu_open.strftime('%l:%M%p')} - #{@business.hour.thu_close.strftime('%l:%M%p')}" if @business.hour.thu_open && @business.hour.thu_close %></td></tr>
          <tr><td class="day_column">Friday:</td><td class="hours_column"><%= "#{@business.hour.fri_open.strftime('%l:%M%p')} - #{@business.hour.fri_close.strftime('%l:%M%p')}" if @business.hour.fri_open && @business.hour.fri_close %></td></tr>
          <tr><td class="day_column">Saturday:</td><td class="hours_column"><%= "#{@business.hour.sat_open.strftime('%l:%M%p')} - #{@business.hour.sat_close.strftime('%l:%M%p')}" if @business.hour.sat_open && @business.hour.sat_close %></td></tr>
          <tr><td class="day_column">Sunday:</td><td class="hours_column"><%= "#{@business.hour.sun_open.strftime('%l:%M%p')} - #{@business.hour.sun_close.strftime('%l:%M%p')}" if @business.hour.sun_open && @business.hour.sun_close %></td></tr>
        </table>
        <% else %>
          Business Hour Data N/A
        <% end %>
      <div class="ui dividing header">Happy Hour Details</div>
        <% if @business.hour %>
        <table>
          <tr><td class="day_column">Monday:</td><td class="hours_column"><%= "#{@business.hour.mon_start.strftime('%l:%M%p')} - #{@business.hour.mon_end.strftime('%l:%M%p')}" if @business.hour.mon_start && @business.hour.mon_end %></td></tr>
          <tr><td class="day_column">Tuesday:</td><td class="hours_column"><%= "#{@business.hour.tue_start.strftime('%l:%M%p')} - #{@business.hour.tue_end.strftime('%l:%M%p')}" if @business.hour.tue_start && @business.hour.tue_end %></td></tr>
          <tr><td class="day_column">Wednesday:</td><td class="hours_column"><%= "#{@business.hour.wed_start.strftime('%l:%M%p')} - #{@business.hour.wed_end.strftime('%l:%M%p')}" if @business.hour.wed_start && @business.hour.wed_end %></td></tr>
          <tr><td class="day_column">Thursday:</td><td class="hours_column"><%= "#{@business.hour.thu_start.strftime('%l:%M%p')} - #{@business.hour.thu_end.strftime('%l:%M%p')}" if @business.hour.thu_start && @business.hour.thu_end %></td></tr>
          <tr><td class="day_column">Friday:</td><td class="hours_column"><%= "#{@business.hour.fri_start.strftime('%l:%M%p')} - #{@business.hour.fri_end.strftime('%l:%M%p')}" if @business.hour.fri_start && @business.hour.fri_end %></td></tr>
          <tr><td class="day_column">Saturday:</td><td class="hours_column"><%= "#{@business.hour.sat_start.strftime('%l:%M%p')} - #{@business.hour.sat_end.strftime('%l:%M%p')}" if @business.hour.sat_start && @business.hour.sat_end %></td></tr>
          <tr><td class="day_column">Sunday:</td><td class="hours_column"><%= "#{@business.hour.sun_start.strftime('%l:%M%p')} - #{@business.hour.sun_end.strftime('%l:%M%p')}" if @business.hour.sun_start && @business.hour.sun_end %></td></tr>
        </table>
        <% else %>
          Happy Hour Data N/A
        <% end %>
    </div>
  </div>
</div>



<div class="ui modal">
 <i class="close icon"></i>
 <div class="header">
   Upload a Photo for <%= @business.name %>
 </div>
 <div class="content">
    <div class="ui small form segment">
      <div class="description">
        <%= form_for [@business, Photo.new] do |f| %>
        <div class="field">
          <label>Photo:</label> <%= f.file_field :photo, class: "ui input" %>
        </div>
        <div class="field">
          <label>Caption:</label> <%= f.text_field :caption, class: "ui input" %>
        </div>
        <div class="field">
          <%= f.submit "Add Photo", class: "ui button" %>
        <% end %>
        </div>
      </div>
    </div>
 </div>
 <div class="actions">
   <div class="ui button">Cancel</div>
 </div>
</div>
<%= render 'businesses/map' %>