config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  resources :users, :businesses do
    resources :comments, :reviews, :photos, :hours
  end

  get '/test' => 'pages#test'
  patch '/hours' => 'hours#update'

  get 'businesses/index'

  # Authentication Routes
  get '/signup' => 'users#new'
  post '/signup' => 'users#post'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews
  has_many :businesses, through: :photos
  has_many :businesses, through: :reviews
  has_secure_password
  mount_uploader :photo, ProfileUploader

  def admin?
    self.role == 'admin'
  end

  def self.from_omniauth(auth)
    where({:provider => auth['provider'], :uid => auth['uid']}).first_or_initialize.tap do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      user.name = auth['info']['name']
      user.oauth_token = auth['credentials']['token']
      user.oauth_expires_at = Time.at(auth['credentials']['expires_at'])
      user.password = "dasdfa#{rand(12345)}"
      user.first_name = auth['info']['first_name']
      user.last_name = auth['info']['last_name']
      user.email = auth['info']['email']
      user.username = auth['info']['email']
      user.nickname = auth['info']['first_name']
      user.website = auth['info']['link']
      user.save!
    end
  end  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)

		if @user.save
			session[:user_id] = @user.id.to_s
			flash[:success] = "You've successfully created an account."
			redirect_to('/')
		else
			flash[:failure] = "Something went wrong. Your account wasn't created."
			redirect_to('/signup')
		end
	end

	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])

		if @user.update_attributes(userprofile_params)
			redirect_to user_path(@user.id)
		else
			render edit
		end
	end

	private
		def user_params
			params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name, :location, :hometown, :nickname, :headline, :website)
		end

		def userprofile_params
			params.require(:user).permit(:first_name, :last_name, :email, :username, :location, :hometown, :nickname, :photo, :headline, :website, :password, :password_confirmation)
		end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_menu_bar.html.erb
<div class="menubar">
  <div class="ui secondary menu">
    <%= link_to raw("<i class='home icon'></i> Home"), root_path, class: "item" %>
    <%= link_to raw("<i class='food icon'></i> Happy Hour Listing"), businesses_path, class: "item" %>
    <% if current_user %>
    <%= link_to raw("<i class='plus icon'></i> Add Business"), new_business_path, class: "item" if current_user.admin? %>
    <% end %>
    <div class="right menu">
    <%= link_to raw("<i class='arrow left icon'></i> Back to Profile"), user_path(current_user.id), class: "item" if current_user && params[:action] == 'edit' %>
    <%= link_to raw("<i class='user icon'></i> Edit Profile"), edit_user_path(current_user.id), class: "item" if current_user && params[:action] == 'show' %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<%= render 'users/menu_bar' %>
<div class="ui two column grid">
	<div class="column">
	<div class="ui small form segment">
			<center><%= image_tag @user.photo.url, class: "borderit" if @user.photo %></center><br><br>

	<%= form_for @user do |f| %>
		<div class="field">
		<label>Upload a Photo</label><%= f.file_field :photo, class: "ui input"  %>
		</div>

	<%= f.submit "Upload Photo", class: "ui green button" %>

	</div>



	<% end %>

	</div>
	<div class="column">
		<div class="ui small form segment">
		<h5 class="ui dividing header">Profile Details</h5>
		<%= form_for @user do |f| %>
			<div class="field">
				<label>First Name</label><%= f.text_field :first_name, class: "ui input"  %>
			</div>
			<div class="field">
				<label>Last Name</label><%= f.text_field :last_name, class: "ui input"  %>
			</div>
			<div class="field">
				<label>Username</label><%= f.text_field :username, class: "ui input"  %>
			</div>
			<div class="field">
				<label>Location</label><%= f.text_field :location, class: "ui input"  %>
			</div>
			<div class="field">
				<label>Hometown</label><%= f.text_field :hometown, class: "ui input"  %>
			</div>
			<div class="field">
				<label>Nickname</label><%= f.text_field :nickname, class: "ui input"  %>
			</div>
			<div class="field">
				<label>Headline / Quote</label><%= f.text_field :headline, class: "ui input"  %>
			</div>
			<div class="field">
				<label>Website</label><%= f.text_field :website, class: "ui input"  %>
			</div>
			<%= f.submit "Update Profile", class: "ui blue button" %>
		<% end %>
		</div>

		<div class="ui small form segment">
		<h5 class="ui dividing header">Change Password</h5>
		<%= form_for @user do |f| %>
			<div class="field">
				<label>New Password</label><%= f.password_field :password, class: "ui input"  %>
			</div>
			<div class="field">
				<label>Confirm Password</label><%= f.password_field :password_confirmation, class: "ui input"  %>
			</div>
			<%= f.submit "Update Password", class: "ui blue button" %>
		<% end %>
		</div>

	</div>
</div>

app/views/users/new.html.erb
<%#= form_for @user do |f| %>
<div class="ui attached message">
  <div class="header">
    Welcome to #happyLA!
  </div>
  <p>Fill out the form below to sign-up for a new account</p>
</div>
<%= form_for @user, :html => { :class => "ui form attached fluid segment" } do |f| %>
  <div class="two fields">
    <div class="field">
      <label>First Name</label>
      <%= f.text_field :first_name, placeholder: "First Name..." %>
    </div>
    <div class="field">
      <label>Last Name</label>
      <%= f.text_field :last_name, placeholder: "Last Name..." %>
    </div>
  </div>
  <div class="two fields">
    <div class="field">
      <label>Username</label>
      <%= f.text_field :username, placeholder: "Desired username..." %>
    </div>
    <div class="field">
      <label>E-mail</label>
      <%= f.text_field :email, placeholder: "E-mail address..." %>
    </div>
  </div>
  <div class="field">
    <label>Password</label>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <label>Confirm Password</label>
    <%= f.password_field :password_confirmation %>
  </div>
  <%= f.submit "Create Account", class: "ui blue submit button" %>
<% end %>
<div class="ui bottom attached warning message">
  <i class="icon help"></i>
  Already signed up? <%= link_to "Login here", '/login' %> instead.
</div>


      <div id="user-widget" style="width: 300px; margin: 0 auto;">
        <% if current_user %>
          Welcome <strong><%= current_user.name %></strong>!
          <%= link_to "Sign out", signout_path, id: "sign_out" %>
        <% else %>
          <center>- or -</center><br>
          <center><%= link_to "Sign Up with Facebook", "/auth/facebook", id: "sign_in", class: "ui facebook button" %></center>
        <% end %>
      </div>

app/views/users/show.html.erb
<%= render 'users/menu_bar' %>

<div class="ui grid">
  <div class="six wide column">
    <div style="width: 327px; height: 327px; border: 1px solid black; background #000; text-align: center;"><%= image_tag @user.photo.url if @user.photo %></div>
    <center><br>
    <h1 class="normalize"><%= "#{@user.first_name} #{@user.last_name}" if @user.first_name && @user.last_name %></h1>
    <span class="subheading"><%= "#{@user.username}: <i>#{@user.headline}</i>".html_safe %></span>

    <strong>Nickname:</strong>
    <p><%= @user.nickname %></p>
    
    <strong>Website:</strong>
    <p><%= link_to @user.website, @user.website %></p>    

    <strong>Current Location:</strong>
    <p><%= @user.location %></p>    

    <strong>Hometown:</strong>
    <p><%= @user.hometown %></p>
    </center>
  </div>
  <div class="ten wide column">
<h5 class="ui dividing header">Recent reviews by <%= @user.first_name %></h5>
<% @user.reviews.each do |review| %>
<div class="recent_businesses_container">
    <div class="ui dividing header"><strong><%= link_to review.business.name, business_path(review.business.id) if review.business %></strong> <span class="small_text"><% if review.title %>"<% end %><%= review.title %><% if review.title %>"<% end %></span></div>
    <span class="small_text"><%= simple_format(review.body) %></span>
</div>
<% end %>

  </div>
</div>