config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  resources :users, :businesses do
    resources :comments, :reviews, :photos, :hours
  end

  get '/test' => 'pages#test'
  patch '/hours' => 'hours#update'

  get 'businesses/index'

  # Authentication Routes
  get '/signup' => 'users#new'
  post '/signup' => 'users#post'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	def new
		@business = Business.find(params[:business_id])
		@review = @business.reviews.new
	end

	def create
		@business = Business.find(params[:business_id])
		@review = @business.reviews.new(review_params)
		@review.user_id = current_user.id

		if @review.save
			redirect_to business_path(@business)
		else
			render business_path(@business)
		end
	end

	private
		def review_params
			params.require(:review).permit(:body, :rating, :title)
		end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/new.html.erb
<div class="menubar">
  <div class="ui secondary menu">
    <%= link_to raw("<i class='home icon'></i> Home"), root_path, class: "item" %>
    <%= link_to raw("<i class='food icon'></i> Back to #{@business.name}"), business_path(@business.id), class: "item" if current_user.admin? && params[:action] == 'new' %>
    <%= link_to raw("<i class='food icon'></i> Happy Hour Listing"), businesses_path, class: "item" %>
    <% if current_user %>
    <%= link_to raw("<i class='plus icon'></i> Add Business"), new_business_path, class: "item" if current_user.admin? %>
    <%= link_to raw("<i class='edit icon'></i> Edit Business"), edit_business_path, class: "item" if current_user.admin? && params[:action] == 'show' %>
    <% if current_user.admin? && params[:action] == 'show' %><%= link_to raw("<i class='remove icon'></i> Delete Business"), :business, class: "item", method: :delete, data: {confirm: "Are you sure you want to delete this listing? This will remove all associated reviews, photos, and business information."} %><% end %>
    <% end %>
    <div class="right menu">
    <%= link_to raw("<i class='user icon'></i> About Me"), user_path(current_user.id), class: "item" if current_user %>
    </div>
  </div>
</div>


<h4 class="ui dividing header">Add a Review for <%= @business.name %></h4>

<div class="ui small form segment">
<%= form_for [@business, @review] do |f| %>
  <div class="field">
  <label>Review Title / Shout</label>
  <%= f.text_field :title, class: "ui input" %>
  </div>
  <div class="field">
  <label>Rating</label>
  <%= select_tag 'review[rating]', "<option value='5'>5 Stars</option><option value='4'>4 Stars</option><option value='3'>3 Stars</option><option value='2'>2 Stars</option><option value='1'>1 Star</option>".html_safe, class: "ui search dropdown normalize", id: "review_rating" %>
  </div>
  <div class="field">
  <label>Review</label>
  <%= f.text_area :body, class: "ui input" %>
  </div>
  <%= f.submit "Add Review", class: "ui green button" %>

<% end %>
</div>